---
- name: Update package cache
  dnf:
    update_cache: yes

- name: Install Docker 
  dnf:
    name:
      - docker
    state: latest

- name: Start the Docker Service in CentOS
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Adding the current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Creating a directory for Dockerfile
  file:
    path: /home/jem/docker_config
    state: directory

- name: Copying the Dockerfile
  copy:
    src: /home/jem/HOA11.1/CentOS_Docker/Dockerfile
    dest: /home/jem/docker_config
    owner: jem
    group: jem

- name: Creating volume
  file:
    path: /home/jem/pages
    state: directory

- name: Build Docker image
  command: "docker build -t lamp-userver:1.0 /home/jem/docker_config"
  
- name: Deploying container
  community.docker.docker_container:
    name: lamp-userver
    image: lamp-userver:1.0
    state: started
    exposed_ports:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - /home/jem/pages:/var/www/html

- block:
  - name: Verify if lamp-userver container is running
    shell: docker ps
    register: container_status

  - debug:
      msg: "{{ container_status }}"
